import { WorkflowEntrypoint } from "cloudflare:workers";

export class ExecutiveSummaryWorkflow extends WorkflowEntrypoint {
  async run(event, step) {
    const env = this.env;
    const { email, month, year } = event.payload;
    const id = event.instanceId;

    await step.do("mark running", async () => {
      await env.DB.prepare(
        `UPDATE executive_summaries SET status='running', updated_at=datetime('now') WHERE id=?`
      ).bind(id).run();
    });

    try {
      await step.do("generate and send executive summary", async () => {
        // 2) Pull feedback for month (feedback table: created_at, body, title, source)
        const { start, end } = monthRange(month, year);
        const rows = await env.DB.prepare(
          `SELECT source, title, body, created_at
           FROM feedback
           WHERE created_at >= ? AND created_at < ?
           ORDER BY created_at ASC`
        ).bind(start, end).all();

        // 3) Summarize via Workers AI
        const summary = await generateExecutiveSummary(env.AI, rows.results || [], { month, year });

        // 4) Store final summary
        await env.DB.prepare(
          `UPDATE executive_summaries
           SET summary=?, updated_at=datetime('now')
           WHERE id=?`
        ).bind(summary, id).run();

        // 5) Send email via Resend
        await sendEmail(env, { to: email, subject: `Cloudflare Executive Summary – ${monthName(month)} ${year}`, summary, month, year });

        // 6) Mark status sent
        await env.DB.prepare(
          `UPDATE executive_summaries SET status='sent', updated_at=datetime('now') WHERE id=?`
        ).bind(id).run();
      });
    } catch (err) {
      await env.DB.prepare(
        `UPDATE executive_summaries
         SET status='failed', error=?, updated_at=datetime('now')
         WHERE id=?`
      ).bind(String(err?.message || err), id).run();
      throw err;
    }
  }
}

function monthRange(month, year) {
  const start = new Date(Date.UTC(year, month - 1, 1));
  const end = new Date(Date.UTC(year, month, 1));
  const iso = (d) => d.toISOString().slice(0, 10);
  return { start: iso(start) + "T00:00:00Z", end: iso(end) + "T00:00:00Z" };
}

function monthName(month) {
  const names = ["", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
  return names[month] || String(month);
}

async function sendEmail(env, { to, subject, summary, month, year }) {
  const apiKey = env.RESEND_API_KEY;
  if (!apiKey) throw new Error("RESEND_API_KEY not configured");

  const from = env.RESEND_FROM_EMAIL || "Cloudflare Intelligence <onboarding@resend.dev>";
  const html = `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>${subject}</title></head>
<body style="font-family: system-ui, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;">
  <h1 style="font-size: 1.25rem; color: #2C7BFF;">Cloudflare Executive Summary</h1>
  <p style="color: #666; font-size: 0.875rem;">${monthName(month)} ${year}</p>
  <div style="margin-top: 24px; white-space: pre-wrap;">${escapeHtml(summary || "No summary generated.")}</div>
  <p style="margin-top: 32px; font-size: 0.75rem; color: #999;">This summary was generated by Cloudflare Intelligence from product feedback.</p>
</body>
</html>`;

  const res = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "Authorization": `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      from,
      to: [to],
      subject,
      html,
    }),
  });

  if (!res.ok) {
    const errText = await res.text();
    throw new Error(`Resend API error: ${res.status} ${errText}`);
  }
}

function escapeHtml(text) {
  if (!text) return "";
  return String(text)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

async function generateExecutiveSummary(AI, feedbackRows, { month, year }) {
  const maxItems = 120;
  const items = feedbackRows.slice(0, maxItems).map((r) => ({
    source: r.source,
    title: r.title,
    content: r.body || r.content,
    created_at: r.created_at,
  }));

  const prompt = `
You are a senior Cloudflare Product Manager.
Write an executive summary for ${month}/${year} based on the feedback items below.

Rules:
- Start with a capital letter.
- No “a total of…”, no percentages, no volume stats unless critical.
- Focus on product insights: top themes, user pain, suspected root causes, impacted products, and recommended next actions.
- 6–10 sentences max.
- Output plain text only.

Feedback items (JSON):
${JSON.stringify(items)}
`;

  const res = await AI.run("@cf/meta/llama-3.1-8b-instruct", {
    messages: [{ role: "user", content: prompt }],
    max_tokens: 350,
  });

  return (res?.response || "").trim();
}
